- .dependabot/config.yml
Hello,
This PR intend to set up dependabot which create automatically a Pull Request when some vulnerabilities are found in your dependencies.
Regards,
Alexandre.
> setting up dependabot

- README.adoc
Adding licence on ARA picture.
> add ara image license

- client/package-lock.json
- database/pom.xml
- generated-cucumber-report/pom.xml
- lib/pom.xml
- pom.xml
- server/pom.xml
- server/src/main/java/com/decathlon/ara/service/dto/problem/ProblemWithPatternsDTO.java
- server/src/main/java/com/decathlon/ara/service/dto/type/TypeWithSourceCodeDTO.java
- server/src/test/java/com/decathlon/ara/report/service/ExecutedScenarioExtractorServiceTest.java
> feat: Move from SpringBoot's parent pom to Decathlon's one

- doc/integrator/main/IntegratorDocumentation.adoc
- doc/uploads/UploadPostman.adoc
> feat: Add the documentation about how to upload reports on Postman

- README.adoc
- docker-compose.yml
> feat: Update the project to easily install it locally without building it

- .circleci/config.yml
- README.adoc
- client/package.json
- client/pom.xml
- docker-compose.yml
- final/Dockerfile
Fix a mistake-push on version/4.0.0 (#83)
> feat: Add CircleCI release & build pipelines

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
Add bug reports, feature requests, and questions Github templates to the repository to help contributors to give us feedback.
> feat: Add issue templates

- .github/pull_request_template.md
> feat: Add the GitHub pull request template

- .circleci/config.yml
No changes in ARA's features.
Fix the CircleCI pipeline to build all the branches and not only `master` and `version/.*` (using `mvn` build only). 
Issue #146 
> fix: Build the App's JAR in all branches on CircleCI

- client/package-lock.json
- client/src/libs/exception-util.js
- database/instance/manage-db.sh
Optimize the execution and problems pages which hungs indefinitely on big executions. (#81)
Refactor a regex which is responsible of trimming the backend exceptions names from the stacktrace.
> chore: Optimize the Execution & Problems pages when lot of errors needs to be displayed

- LICENSE
Add the year of release and the owner of the project.
N/A
N/A
> chore: update Licence information

- client/package.json
Version rollback due to npm build failed
> fix: Rollback http proxy version upgrade

- client/src/views/execution.vue
fix issue 67 chg the color of the criteria columns
Closes #67 
> fix: issue 67 chg the color of the criteria columns

- client/src/components/crud.vue
- client/src/components/functionality-export-popup.vue
- client/src/styles/common.css
- client/src/views/management-settings.vue
- database/instance/manage-db.sh
- final/entrypoint.sh
- server/pom.xml
- server/src/main/java/com/decathlon/ara/cartography/AraExporter.java
- server/src/main/java/com/decathlon/ara/cartography/ExportField.java
- server/src/main/java/com/decathlon/ara/cartography/Exporter.java
- server/src/main/java/com/decathlon/ara/cartography/SquashExporter.java
- server/src/main/java/com/decathlon/ara/service/FunctionalityService.java
- server/src/main/java/com/decathlon/ara/service/dto/functionality/ExporterInfoDTO.java
- server/src/main/java/com/decathlon/ara/service/dto/functionality/FunctionalityDTO.java
- server/src/main/java/com/decathlon/ara/web/rest/FunctionalityResource.java
- server/src/test/java/com/decathlon/ara/cartography/AraExporterTest.java
- server/src/test/java/com/decathlon/ara/cartography/ExporterTest.java
- server/src/test/java/com/decathlon/ara/cartography/SquashExporterTest.java
This change will brings a new functionality exporter option to integrate functionalities in SquashTM.
* Update the list of available exporters to add a list of required fields which acts a list of required informations (by default this list is empty)
* Display this list dynamically in the export popup in the front end if it's not empty.
> feat: add a squash export

- client/src/components/error-popups.vue
No feature impacted
Remove last occurrences of execution-shortener in export-popup.vue
> fix: Remove last occurrences of execution-shortener

- client/pom.xml
- database/pom.xml
- final/pom.xml
- generated-cucumber-report/pom.xml
- lib/pom.xml
- pom.xml
- server/pom.xml
Prepare the release of the version 4.1.0
Change the version number in all the POM files to remove the SNAPSHOT in them.
> chore: Prepare Release 4.1.0

- server/src/main/java/com/decathlon/ara/Messages.java
- server/src/main/java/com/decathlon/ara/service/ProjectService.java
> fix: switch default project

- client/pom.xml
- database/pom.xml
- final/pom.xml
- generated-cucumber-report/pom.xml
- lib/pom.xml
- pom.xml
- server/pom.xml
Only a technical change.
Change the version of the POM files to the prepare the next release : `5.0.0-SNAPSHOT`.
> chore: Add the new release's version to the POM files

- README.adoc
No behaviour modification. Only a documentation update to bypass the Docker internal network DNS limitation on GNU/Linux.
Close #222
* Adapt the main README.adoc to use the static ip `172.17.0.1` instead of `docker.internal.host` DNS on GNU/Linux in the docker-compose file.
> chore: Add an additional step to locally run ARA on Linux

- client/pom.xml
- database/pom.xml
- doc/developer/DeveloperDocumentation.adoc
- final/pom.xml
- generated-cucumber-report/pom.xml
- lib/pom.xml
- pom.xml
- server/pom.xml
- src/site/site.xml
> chore: add maven site generation

- .circleci/config.yml
> chore: cherry-picking the following commit -> Separate the docker build&push for nightly & latest

- client/src/components/nrt-cycle.vue
> feat: add First data-nrt-id to ARA for E2E testing

- client/src/components/execution-actions-button.vue
- client/src/components/nrt-cycle-quality.vue
- client/src/components/nrt-cycle.vue
- client/src/components/nrt-run.vue
- client/src/components/nrt-team.vue
- client/test/cypress/scenarii/user-journey executions and errors.feature
- client/test/cypress/support/fragments/executions.js
- client/test/cypress/support/stepDefinitions/executionsAndErrorsSteps.js
> feat: add data-nrt ids to ARA for E2E testing - executions and errors tab

- database/instance/manage-db.bat
- database/instance/manage-db.sh
> chore: add windows database install script

- client/src/components/execution-actions-button.vue
- client/src/components/nrt-cycle-quality.vue
- client/src/components/nrt-cycle.vue
- client/src/components/nrt-run.vue
- client/src/components/nrt-team.vue
- client/test/cypress/fixtures/executions_latest.json
- client/test/cypress/scenarii/user-journey executions and errors.feature
- client/test/cypress/scenarii/user-journey-executions-and-errors.feature
- client/test/cypress/support/commands.js
- client/test/cypress/support/fragments/commun.js
- client/test/cypress/support/fragments/executions.js
- client/test/cypress/support/stepDefinitions/executionsAndErrorsSteps.js
> feat: Update data-nrt and feature and mock api response

- database/src/main/java/com/decathlon/ara/repository/ExecutionRepository.java
- server/src/main/java/com/decathlon/ara/ci/service/ExecutionIndexerService.java
- server/src/test/java/com/decathlon/ara/ci/service/ExecutionIndexerServiceTest.java
> fix: assign existing problems to execution errors

- server/src/main/java/com/decathlon/ara/scenario/common/upload/ScenarioUploader.java
> fix: upload scenarios

- client/pom.xml
- database/pom.xml
- final/pom.xml
- generated-cucumber-report/pom.xml
- lib/pom.xml
- pom.xml
- server/pom.xml
> chore: update pom before release

- CHANGELOG.adoc
- doc/demo/DemoWalkthrough.adoc
- doc/developer/DeveloperDocumentation.adoc
- doc/integrator/main/IntegratorDocumentation.adoc
- doc/uploads/HowItWorks.adoc
- doc/uploads/UploadCucumber.adoc
- doc/uploads/UploadPostman.adoc
- doc/user/functionalities/CreateAndMoveFunctionalities.adoc
- doc/user/main/UserDocumentation.adoc
- server/README.adoc
> docs: remove broken docker links

- client/test/cypress/fixtures/executions_latest.json
- client/test/cypress/fixtures/teams.json
- client/test/cypress/scenarii/user-journey-executions-and-errors.feature
- client/test/cypress/support/stepDefinitions/executionsAndErrorsSteps.js
> test: fix nrt by adding teams fixture

- .circleci/config.yml
- client/pom.xml
- database/pom.xml
- final/pom.xml
- generated-cucumber-report/pom.xml
- lib/pom.xml
- pom.xml
- server/pom.xml
> fix: publish complete ARA image

- client/cypress.json
- client/src/main.js
> fix: put hashbang back due to navigation problems

- client/src/components/nrt-cycle.vue
- client/test/cypress/fixtures/executions_history.json
- client/test/cypress/fixtures/executions_latest.json
- client/test/cypress/scenarii/user-journey-executions-and-errors.feature
- client/test/cypress/support/fragments/commun.js
- client/test/cypress/support/fragments/executions.js
- client/test/cypress/support/stepDefinitions/executionsAndErrorsSteps.js
> test: add new nrt on executions part

- database/src/main/java/com/decathlon/ara/repository/CycleDefinitionRepository.java
- server/src/main/java/com/decathlon/ara/loader/DemoExecutionLoader.java
- server/src/main/java/com/decathlon/ara/service/CycleDefinitionService.java
- server/src/main/java/com/decathlon/ara/service/ExecutionFilesProcessorService.java
- server/src/main/java/com/decathlon/ara/service/ExecutionService.java
- server/src/test/java/com/decathlon/ara/service/ExecutionServiceTest.java
> fix: clean incoming folder after indexing executions

- client/pom.xml
- database/pom.xml
- final/pom.xml
- generated-cucumber-report/pom.xml
- lib/pom.xml
- pom.xml
- server/pom.xml
> chore: release version 5.0.3

- client/src/components/functionality-node.vue
- client/src/views/functionality-cartography.vue
- database/src/main/java/com/decathlon/ara/repository/FunctionalityRepository.java
- server/src/main/java/com/decathlon/ara/Messages.java
- server/src/main/java/com/decathlon/ara/service/FunctionalityService.java
- server/src/main/java/com/decathlon/ara/service/dto/request/MoveFunctionalitiesDTO.java
- server/src/main/java/com/decathlon/ara/web/rest/FunctionalityResource.java
- server/src/test/java/com/decathlon/ara/service/FunctionalityServiceTest.java
> feat: move several functionalities

- client/src/libs/util.js
- client/src/views/functionality-cartography.vue
- database/src/main/java/com/decathlon/ara/repository/FunctionalityRepository.java
- server/src/main/java/com/decathlon/ara/service/FunctionalityService.java
- server/src/main/java/com/decathlon/ara/web/rest/FunctionalityResource.java
- server/src/test/java/com/decathlon/ara/service/FunctionalityServiceTest.java
> feat: delete several functionalities

- doc/user/main/UserDocumentation.adoc
> fix: remove Karate reference in user documentation

- client/src/views/functionality-cartography.vue
> fix: remove cartography infinite loading

- client/src/components/functionality-node.vue
- client/src/views/functionality-cartography.vue
> feat: enhance cartography multiple selection

- client/test/cypress/fixtures/executions_history.json
- client/test/cypress/scenarii/user-journey-executions-and-errors.feature
- client/test/cypress/support/fragments/commun.js
- client/test/cypress/support/stepDefinitions/executionsAndErrorsSteps.js
> test: add scenario for not all green execution

- client/src/components/projects-select.vue
- client/src/views/functionality-cartography.vue
> fix: reset functionalities selection on project change

- client/src/components/functionality-node.vue
> feat: highlight selected functionality lines

- client/src/routes.js
- client/src/views/not-found.vue
> feat: add 404 page

- client/src/views/functionality-cartography.vue
> fix: add loader when no settings while consulting cartography page

- client/src/views/functionality-cartography.vue
> fix: enable selecting all the folder content without selecting the folder itself on cartography page

- .github/workflows/build-back.yaml
- .github/workflows/build-front.yaml
- charts/stable/Chart.yaml
- charts/stable/templates/deploy-api.yaml
- charts/stable/templates/deploy-ui.yaml
- code/api/database/pom.xml
- code/api/generated-cucumber-report/pom.xml
- code/api/lib/pom.xml
- code/api/pom.xml
- code/api/server/pom.xml
> ⬆️  Upgrade to 7.0.4

- server/src/main/java/com/decathlon/ara/scenario/cucumber/bean/Argument.java
- server/src/main/java/com/decathlon/ara/scenario/cucumber/bean/Comment.java
- server/src/main/java/com/decathlon/ara/scenario/cucumber/bean/DocString.java
- server/src/main/java/com/decathlon/ara/scenario/cucumber/bean/Element.java
- server/src/main/java/com/decathlon/ara/scenario/cucumber/bean/Embedded.java
- server/src/main/java/com/decathlon/ara/scenario/cucumber/bean/Feature.java
- server/src/main/java/com/decathlon/ara/scenario/cucumber/bean/Hook.java
- server/src/main/java/com/decathlon/ara/scenario/cucumber/bean/Match.java
- server/src/main/java/com/decathlon/ara/scenario/cucumber/bean/Result.java
- server/src/main/java/com/decathlon/ara/scenario/cucumber/bean/Row.java
- server/src/main/java/com/decathlon/ara/scenario/cucumber/bean/Step.java
- server/src/main/java/com/decathlon/ara/scenario/cucumber/bean/Tag.java
> fix: ignore unknown fields when uploading Cucumber scenarios

- charts/stable/Chart.yaml
- code/api/database/pom.xml
- code/api/generated-cucumber-report/pom.xml
- code/api/lib/pom.xml
- code/api/pom.xml
- code/api/server/pom.xml
- code/api/server/src/main/java/com/decathlon/ara/scenario/cucumber/bean/Argument.java
- code/api/server/src/main/java/com/decathlon/ara/scenario/cucumber/bean/Comment.java
- code/api/server/src/main/java/com/decathlon/ara/scenario/cucumber/bean/DocString.java
- code/api/server/src/main/java/com/decathlon/ara/scenario/cucumber/bean/Element.java
- code/api/server/src/main/java/com/decathlon/ara/scenario/cucumber/bean/Embedded.java
- code/api/server/src/main/java/com/decathlon/ara/scenario/cucumber/bean/Feature.java
- code/api/server/src/main/java/com/decathlon/ara/scenario/cucumber/bean/Hook.java
- code/api/server/src/main/java/com/decathlon/ara/scenario/cucumber/bean/Match.java
- code/api/server/src/main/java/com/decathlon/ara/scenario/cucumber/bean/Result.java
- code/api/server/src/main/java/com/decathlon/ara/scenario/cucumber/bean/Row.java
- code/api/server/src/main/java/com/decathlon/ara/scenario/cucumber/bean/Step.java
- code/api/server/src/main/java/com/decathlon/ara/scenario/cucumber/bean/Tag.java
> Feat/merge 7.0.0

- charts/stable/Chart.yaml
- code/api/database/pom.xml
- code/api/generated-cucumber-report/pom.xml
- code/api/lib/pom.xml
- code/api/pom.xml
- code/api/server/pom.xml
> ⬆️  Upgrade to 7.1.1

- server/src/main/java/com/decathlon/ara/scenario/postman/service/PostmanScenarioIndexerService.java
When uploading postman reports, some files causes the upload to crash, but can be ignored to let ARA process the remaining files. Also fixes a potential NullPointerException.
> fix: ignore incorrect files while uploading postman scenarios

- .github/workflows/release.yaml
- charts/stable/Chart.yaml
- code/api/database/pom.xml
- code/api/generated-cucumber-report/pom.xml
- code/api/lib/pom.xml
- code/api/pom.xml
- code/api/server/pom.xml
> chart-releaser

- client/src/views/functionality-cartography.vue
Closes #336
**On the Functionalities/cartography view, display the number of selected items**
closes #336 
**Add a new item in counts object, increment it when item is checked**
> feat: display number of selected functionalities

- client/src/views/functionality-cartography.vue
In the cartography view, when selecting all, functionalities count is not correctly updated
> fix: selection count bug when selecting all

- README.adoc
- code/Makefile
- code/api/Makefile
- code/api/server/pom.xml
- code/docker-compose.yaml
- code/web-ui/.dockerignore
- code/web-ui/Makefile
- code/web-ui/config/index.js
- doc/developer/DeveloperDocumentation.adoc
> Refacto make and run

- client/pom.xml
- database/pom.xml
- final/pom.xml
- generated-cucumber-report/pom.xml
- lib/pom.xml
- pom.xml
- server/pom.xml
> chore: update to v6.1.1

- .github/workflows/build-back.yaml
- .github/workflows/build-front.yaml
- charts/stable/Chart.yaml
- charts/stable/templates/deploy-api.yaml
- charts/stable/templates/deploy-ui.yaml
- charts/stable/values.yaml
- code/api/database/pom.xml
- code/api/generated-cucumber-report/pom.xml
- code/api/lib/pom.xml
- code/api/pom.xml
- code/api/server/pom.xml
Add system for RC
Add system for RC
> chore: add release-candidate system

- charts/stable/Chart.yaml
- charts/stable/templates/deploy-api.yaml
- charts/stable/templates/deploy-ui.yaml
- charts/stable/values.yaml
- code/api/database/pom.xml
- code/api/generated-cucumber-report/pom.xml
- code/api/lib/pom.xml
- code/api/pom.xml
- code/api/server/pom.xml
> Test rc system

- charts/stable/Chart.yaml
- charts/stable/templates/deploy-api.yaml
- charts/stable/templates/deploy-db.yaml
- charts/stable/templates/deploy-ui.yaml
- charts/stable/values.yaml
- code/api/database/pom.xml
- code/api/generated-cucumber-report/pom.xml
- code/api/lib/pom.xml
- code/api/pom.xml
- code/api/server/pom.xml
> ⬆️  Upgrade to 7.1.6

- code/web-ui/config/default.conf.template
- code/web-ui/cypress.json
- code/web-ui/src/main.js
> feat: use vue history mode

- code/web-ui/src/views/functionality-cartography.vue
> fix: clear all fitler functionnality

- .github/workflows/build-back.yaml
- .github/workflows/build-front.yaml
- .github/workflows/build-rc-back.yaml
- .github/workflows/build-rc-front.yaml
- .github/workflows/upgrade-release.yaml
- code/Makefile
Create a better ci rc system
With GA
> chore: adapt ci rc system

- .dependabot/config.yml
> fix: update dependabot config file

- charts/stable/Chart.yaml
- code/api/database/pom.xml
- code/api/generated-cucumber-report/pom.xml
- code/api/lib/pom.xml
- code/api/pom.xml
- code/api/server/pom.xml
- code/web-ui/package-lock.json
- code/web-ui/package.json
> chore: ⬆️  Upgrade to 7.2.4

- charts/stable/Chart.yaml
- charts/stable/templates/config.yaml
- code/api/database/pom.xml
- code/api/generated-cucumber-report/pom.xml
- code/api/lib/pom.xml
- code/api/pom.xml
- code/api/server/pom.xml
- code/web-ui/package-lock.json
- code/web-ui/package.json
> fix: config map problem

- charts/stable/Chart.yaml
- code/api/database/pom.xml
- code/api/generated-cucumber-report/pom.xml
- code/api/jacoco-aggregation/pom.xml
- code/api/lib/pom.xml
- code/api/pom.xml
- code/api/server/pom.xml
- code/web-ui/package-lock.json
- code/web-ui/package.json
> chore: ⬆️ Upgrade to 7.2.5

- code/web-ui/README.adoc
> Chore: change front title

- code/api/server/src/main/java/com/decathlon/ara/configuration/SwaggerConfiguration.java
- code/api/server/src/main/java/com/decathlon/ara/configuration/authentication/provider/custom/AuthenticationCustomValueConfiguration.java
- code/api/server/src/main/java/com/decathlon/ara/configuration/security/SecurityConfigurer.java
- code/api/server/src/main/java/com/decathlon/ara/configuration/security/jwt/JwtTokenAuthenticationService.java
- code/api/server/src/main/java/com/decathlon/ara/service/authentication/AuthenticationService.java
- code/api/server/src/main/java/com/decathlon/ara/service/authentication/provider/Authenticator.java
- code/api/server/src/main/java/com/decathlon/ara/service/authentication/provider/google/GoogleAuthenticator.java
- code/api/server/src/test/java/com/decathlon/ara/configuration/authentication/AuthenticationConfigurationTest.java
- code/api/server/src/test/java/com/decathlon/ara/configuration/authentication/provider/custom/AuthenticationCustomValueConfigurationTest.java
- code/api/server/src/test/java/com/decathlon/ara/configuration/security/AuthenticationJwtTokenConfigurationTest.java
- code/api/server/src/test/java/com/decathlon/ara/configuration/security/filter/JwtRequestFilterTest.java
- code/api/server/src/test/java/com/decathlon/ara/configuration/security/jwt/JwtTokenAuthenticationServiceTest.java
- code/api/server/src/test/java/com/decathlon/ara/service/authentication/AuthenticationServiceTest.java
- code/api/server/src/test/java/com/decathlon/ara/service/authentication/AuthenticationStrategyTest.java
- code/api/server/src/test/java/com/decathlon/ara/service/authentication/provider/custom/CustomAuthenticatorTest.java
- code/api/server/src/test/java/com/decathlon/ara/service/authentication/provider/github/GithubAuthenticatorTest.java
- code/api/server/src/test/java/com/decathlon/ara/service/authentication/provider/google/GoogleAuthenticatorTest.java
- code/api/server/src/test/java/com/decathlon/ara/service/dto/authentication/response/configuration/provider/AuthenticationProviderConfigurationDTOTest.java
- code/web-ui/src/components/authentication/custom-authentication-button.vue
- code/web-ui/src/components/authentication/github-authentication-button.vue
- code/web-ui/src/components/authentication/google-authentication-button.vue
- code/web-ui/src/components/top-menu.vue
- code/web-ui/src/main.js
- code/web-ui/src/views/login.vue
> fix sonar before deployment

- charts/stable/templates/config.yaml
- charts/stable/templates/deploy-api.yaml
- charts/stable/values.yaml
- code/api/entrypoint.sh
- code/api/server/src/main/java/com/decathlon/ara/configuration/security/SecurityConfigurer.java
- code/api/server/src/main/java/com/decathlon/ara/service/EmailService.java
- code/api/server/src/main/resources/application.properties
- code/api/server/src/test/java/com/decathlon/ara/ci/service/QualityEmailServiceManualTester.java
> feat: optional email and custom conf

- code/api/server/src/main/java/com/decathlon/ara/configuration/security/SecurityConfigurer.java
- code/api/server/src/main/java/com/decathlon/ara/configuration/security/jwt/JwtTokenAuthenticationService.java
- code/api/server/src/main/java/com/decathlon/ara/service/authentication/AuthenticationService.java
- code/api/server/src/main/java/com/decathlon/ara/service/authentication/provider/ProviderAuthenticator.java
- code/api/server/src/main/java/com/decathlon/ara/service/authentication/provider/google/GoogleAuthenticator.java
- code/api/server/src/main/java/com/decathlon/ara/service/dto/authentication/provider/AuthenticatorToken.java
- code/api/server/src/main/java/com/decathlon/ara/service/dto/authentication/provider/AuthenticatorUser.java
- code/api/server/src/main/java/com/decathlon/ara/service/dto/authentication/provider/custom/CustomToken.java
- code/api/server/src/main/java/com/decathlon/ara/service/dto/authentication/provider/custom/CustomUser.java
- code/api/server/src/main/java/com/decathlon/ara/service/dto/authentication/provider/github/GithubToken.java
- code/api/server/src/main/java/com/decathlon/ara/service/dto/authentication/provider/github/GithubUser.java
- code/api/server/src/main/java/com/decathlon/ara/service/dto/authentication/provider/google/GoogleToken.java
- code/api/server/src/main/java/com/decathlon/ara/service/dto/authentication/provider/google/GoogleUser.java
- code/api/server/src/main/java/com/decathlon/ara/service/dto/authentication/response/configuration/provider/AuthenticationProviderConfigurationDTO.java
- code/api/server/src/test/java/com/decathlon/ara/configuration/authentication/provider/custom/AuthenticationCustomValueConfigurationTest.java
- code/api/server/src/test/java/com/decathlon/ara/configuration/security/AuthenticationJwtTokenConfigurationTest.java
- code/api/server/src/test/java/com/decathlon/ara/configuration/security/jwt/JwtTokenAuthenticationServiceTest.java
- code/api/server/src/test/java/com/decathlon/ara/service/authentication/provider/google/GoogleAuthenticatorTest.java
> refactor: remove smells from security configurer

- charts/dev/Chart.yaml
- code/api/database/pom.xml
- code/api/generated-cucumber-report/pom.xml
- code/api/jacoco-aggregation/pom.xml
- code/api/lib/pom.xml
- code/api/pom.xml
- code/api/server/pom.xml
- code/web-ui/package-lock.json
- code/web-ui/package.json
> chore: ⬆️ Upgrade to 8.0.0

- charts/stable/Chart.yaml
- charts/stable/templates/_helpers.tpl
- charts/stable/templates/config.yaml
- charts/stable/templates/deploy-api.yaml
- charts/stable/templates/deploy-ui.yaml
- charts/stable/templates/ingress.yaml
- charts/stable/values.yaml
Auto-release stable from 8.0.0-rc.5
> chore: Release Charts stable 8.0.0

- charts/stable/Chart.yaml
- code/api/database/pom.xml
- code/api/generated-cucumber-report/pom.xml
- code/api/jacoco-aggregation/pom.xml
- code/api/lib/pom.xml
- code/api/pom.xml
- code/api/server/pom.xml
- code/web-ui/package-lock.json
- code/web-ui/package.json
> chore: ⬆️ Upgrade to 8.0.1

- charts/stable/Chart.yaml
- code/Makefile
- code/api/.gitignore
- code/api/Dockerfile
- code/api/database/pom.xml
- code/api/database/src/main/java/com/decathlon/ara/domain/Execution.java
- code/api/database/src/main/java/com/decathlon/ara/repository/custom/impl/ExecutionRepositoryImpl.java
- code/api/database/src/main/resources/db/changelog/changes/h2/20210301165639-h2_migration.yaml
- code/api/database/src/main/resources/db/changelog/changes/mysql/20210225103650-REMOVE_DUPLICATES.sql
- code/api/database/src/main/resources/db/changelog/changes/mysql/20210301105923-ADD_UNIQUE_CONSTRAINTS.yaml
- code/api/database/src/main/resources/db/changelog/changes/postgresql/20210225103650-REMOVE_DUPLICATES.sql
- code/api/database/src/main/resources/db/changelog/changes/postgresql/20210301110642-ADD_UNIQUE_CONSTRAINTS.yaml
- code/api/database/src/main/resources/db/changelog/db.changelog-master-h2.yaml
- code/api/database/src/main/resources/db/changelog/db.changelog-master-mysql.yaml
- code/api/database/src/main/resources/db/changelog/db.changelog-master-postgresql.yaml
- code/api/database/src/main/resources/liquibase-h2.properties
- code/api/database/src/main/resources/liquibase-mysql.properties
- code/api/database/src/main/resources/liquibase-postgresql.properties
- code/api/migration-h2.yaml
- code/api/server/src/main/resources/application-db-h2.properties
- code/api/server/src/main/resources/application-db-mysql.properties
- code/api/server/src/main/resources/application-db.properties
> fix: add execution unique constraint

- charts/stable/Chart.yaml
- charts/stable/templates/deploy-api.yaml
- charts/stable/templates/ingress.yaml
- charts/stable/values.yaml
- code/Makefile
> chore: update to 8.1.0

- code/web-ui/package-lock.json
- code/web-ui/package.json
- code/web-ui/src/components/top-menu.vue
> fix: update top menu version text color

- code/web-ui/package-lock.json
- code/web-ui/package.json
- code/web-ui/src/routes.js
- code/web-ui/src/views/executions.vue
Add a `/projects/${PROJECT_CODE}/executions/framed/png` with png download
Add a feature front with png download when access to the framed vue
> feat: png download

- charts/candidate/Chart.yaml
- charts/candidate/values.yaml
- code/api/api/pom.xml
- code/api/database/pom.xml
- code/api/database/src/main/java/com/decathlon/ara/domain/Communication.java
- code/api/database/src/main/java/com/decathlon/ara/domain/ExecutedScenario.java
- code/api/database/src/main/java/com/decathlon/ara/domain/Functionality.java
- code/api/database/src/main/java/com/decathlon/ara/domain/Problem.java
- code/api/database/src/main/java/com/decathlon/ara/domain/ProblemPattern.java
- code/api/database/src/main/java/com/decathlon/ara/domain/Scenario.java
- code/api/generated-cucumber-report/pom.xml
- code/api/jacoco-aggregation/pom.xml
- code/api/lib/pom.xml
- code/api/pom.xml
Add clue for Hibernate to process lob
Add `@Type` annotation under lob attribute for text
> fix: pg text request process

- charts/candidate/Chart.yaml
- charts/candidate/templates/deploy-api.yaml
Fix api config import in helm env
Add SPRING_CONFIG_IMPORT env var set with configs location mounted by the volume
> fix: helm api config import

- .github/workflows/build-api.yaml
- .github/workflows/build-web-ui.yaml
- .github/workflows/charts-lint.yaml
- .github/workflows/sonar.yaml
Upgrade a Github Action used to skip workflow if no changes
Upgrade to v3.4.0
> chore: upgrade skip GA

- README.adoc
- charts/candidate/Chart.yaml
- charts/candidate/values.yaml
- code/Makefile
- code/api/api/pom.xml
- code/api/api/src/main/resources/application-dev.yaml
- code/api/api/src/main/resources/config-database.yaml
- code/api/database/pom.xml
- code/api/database/src/main/java/com/decathlon/ara/domain/Error.java
- code/api/database/src/main/java/com/decathlon/ara/domain/ExecutedScenario.java
- code/api/database/src/main/java/com/decathlon/ara/domain/ProblemPattern.java
- code/api/database/src/main/java/com/decathlon/ara/domain/Run.java
- code/api/database/src/main/resources/db/changelog/changes/postgresql/20210608163625-create_index.yaml
- code/api/database/src/main/resources/db/changelog/db.changelog-master-postgresql.yaml
- code/api/generated-cucumber-report/pom.xml
- code/api/jacoco-aggregation/pom.xml
- code/api/lib/pom.xml
- code/api/migration-h2.yaml
- code/api/migration-mysql.yaml
- code/api/migration-postgresql.yaml
- code/api/pom.xml
Optimize the request under /api/projects/${projectCode}/executions/latest
Add 4 indexes on:
* executed_scenario(run_id)
* error(executed_scenario_id)
* problem_occurrence(error_id)
* run(execution_id)
> chore: optimize latest exec request

- .github/workflows/sonar.yaml
In order to have a better experience in sonar diff this pr set a project version link to the sonar analysis
Add `-Dsonar.projectVersion=${API_VERSION}-${WEB_UI_VERSION}` parameter to the sonar-scanner run
> chore: add project version for sonar analysis

- .dependabot/config.yml
- .github/workflows/build-api.yaml
- .github/workflows/build-web-ui.yaml
- .github/workflows/charts-lint.yaml
- .github/workflows/quality.yaml
- code/api/api/pom.xml
- code/api/database/pom.xml
- code/api/generated-cucumber-report/pom.xml
- code/api/jacoco-aggregation/pom.xml
- code/api/lib/pom.xml
- code/api/pom.xml
Add codeQL check on build api/web-ui
Add to the Build API and Build WEB UI workflow the codeQL GA : https://github.com/github/codeql-action
> chore: add code-ql check on build

- .github/workflows/quality.yaml
Fix a code QL not still needed step
Remove step checkout HEAD^2 in github workflow quality/codeql
> fix: codeQL pr analysis commit position

- .dependabot/config.yml
- .github/workflows/build-api.yaml
- .github/workflows/build-web-ui.yaml
- .github/workflows/charts-lint.yaml
- .github/workflows/quality.yaml
- code/Makefile
- code/api/build/template/about.jq
Try to factorise some steps across github job
Use 2 new actions to share builded workspace
* https://github.com/actions/upload-artifact
* https://github.com/actions/download-artifact
> chore: opt build pipeline

- .github/workflows/charts-lint.yaml
- charts/candidate/Chart.yaml
- charts/candidate/values.yaml
- code/Makefile
- code/web-ui/build/dev-server.js
- code/web-ui/build/webpack.prod.conf.js
- code/web-ui/build/webpack.test.conf.js
- code/web-ui/config/index.js
- code/web-ui/package-lock.json
- code/web-ui/package.json
- doc/user/authentication/Authentication.adoc
Fix security issue about env sent to build web-ui
Remove `process.env` and set specific env individually
> chore: fix security issue on build web-ui

- charts/candidate/Chart.yaml
- charts/candidate/values.yaml
- code/api/api/pom.xml
- code/api/api/src/main/java/com/decathlon/ara/service/ProblemService.java
- code/api/api/src/test/java/com/decathlon/ara/service/ProblemServiceTest.java
- code/api/database/pom.xml
- code/api/database/src/main/java/com/decathlon/ara/repository/ErrorRepository.java
- code/api/generated-cucumber-report/pom.xml
- code/api/jacoco-aggregation/pom.xml
- code/api/lib/pom.xml
- code/api/pom.xml
Fix PostgreSQL get problems
Remove the order by close to allow postgresql to perform distinct on error
> fix: postgresql problem search

- charts/stable/Chart.yaml
- charts/stable/templates/_helpers.tpl
- charts/stable/templates/config.yaml
- charts/stable/templates/deploy-api.yaml
- charts/stable/values.yaml
Upgrade to chart 9.0.2
Copy chart candidate into chart stable
Change chart stable version from 9.0.2-rc.6 to 9.0.2
> chore: Release chart 9.0.2

- code/api/api/src/main/java/com/decathlon/ara/defect/rtc/RtcDefectAdapter.java
- code/api/api/src/main/java/com/decathlon/ara/service/ArchiveService.java
- code/api/api/src/test/java/com/decathlon/ara/service/ArchiveServiceTest.java
> fix: get rid of sonar vulnerabilities

- charts/candidate/Chart.yaml
- charts/candidate/templates/_helpers.tpl
- charts/candidate/templates/config.yaml
- charts/candidate/templates/db-secret.yaml
- charts/candidate/templates/deploy-api.yaml
- charts/candidate/templates/deploy-db.yaml
- charts/candidate/templates/deploy-ui.yaml
- charts/candidate/templates/ingress.yaml
- charts/candidate/values.yaml
- code/api/api/pom.xml
- code/api/api/src/main/resources/application.yaml
- code/api/database/pom.xml
- code/api/generated-cucumber-report/pom.xml
- code/api/jacoco-aggregation/pom.xml
- code/api/lib/pom.xml
- code/api/pom.xml
Use chart release name in service k8s in order to allow multiple release in same workspace
Add chart release name in all yaml kind name
> feat: chart generic

- code/api/api/src/main/resources/templates/mail/html/nrt-cycle.html
- code/api/api/src/main/resources/templates/mail/html/nrt-run.html
- code/web-ui/Makefile
- code/web-ui/build/template/about.jq
- code/web-ui/config/index.js
- code/web-ui/package-lock.json
- code/web-ui/package.json
- code/web-ui/src/components/error-debug-dropdown.vue
- code/web-ui/src/components/error-popups.vue
- code/web-ui/src/components/execution-actions-button.vue
- code/web-ui/src/components/functionality-coverage-details.vue
- code/web-ui/src/components/nrt-cycle-quality.vue
- code/web-ui/src/components/nrt-ignored-scenarios.vue
- code/web-ui/src/components/nrt-run.vue
- code/web-ui/src/components/top-menu.vue
- code/web-ui/src/main.js
- code/web-ui/src/views/executions.vue
- code/web-ui/src/views/functionality-cartography.vue
- code/web-ui/src/views/problem.vue
- code/web-ui/src/views/raw-executions.vue
> feat: add web-ui version

- charts/candidate/Chart.yaml
- charts/candidate/values.yaml
- code/api/api/pom.xml
- code/api/database/pom.xml
- code/api/database/src/main/java/com/decathlon/ara/domain/ProblemPattern.java
- code/api/database/src/main/resources/db/changelog/changes/postgresql/20210715155609-fix-pattern-seq.yaml
- code/api/database/src/main/resources/db/changelog/db.changelog-master-postgresql.yaml
- code/api/generated-cucumber-report/pom.xml
- code/api/jacoco-aggregation/pom.xml
- code/api/lib/pom.xml
- code/api/pom.xml
Set problem_pattern seq to increment 1 and restart to the next id.
Set problem_pattern seq to increment 1 and restart to the next id.
> fix: problem pattern seq

- charts/candidate/Chart.yaml
- charts/candidate/templates/config.yaml
- charts/candidate/templates/deploy-api.yaml
- charts/candidate/templates/deploy-ui.yaml
- charts/candidate/templates/ingress.yaml
- charts/candidate/values.yaml
- code/api/api/pom.xml
- code/api/api/src/main/java/com/decathlon/ara/configuration/security/SecurityConfigurer.java
- code/api/api/src/main/resources/application.yaml
- code/api/database/pom.xml
- code/api/generated-cucumber-report/pom.xml
- code/api/jacoco-aggregation/pom.xml
- code/api/lib/pom.xml
- code/api/pom.xml
- code/docker-compose-mysql.yaml
- code/docker-compose.yaml
- code/web-ui/Dockerfile
- code/web-ui/config/default.conf.template
- code/web-ui/config/index.js
- code/web-ui/package-lock.json
- code/web-ui/package.json
> feat: expose swagger ui

- charts/stable/Chart.yaml
- charts/stable/templates/_helpers.tpl
- charts/stable/templates/config.yaml
- charts/stable/templates/db-secret.yaml
- charts/stable/templates/deploy-api.yaml
- charts/stable/templates/deploy-db.yaml
- charts/stable/templates/deploy-ui.yaml
- charts/stable/templates/ingress.yaml
- charts/stable/values.yaml
- code/Makefile
> chore: release chart 9.2.0

- code/api/api/src/main/java/com/decathlon/ara/scenario/postman/bean/ItemWithScripts.java
- code/api/api/src/main/java/com/decathlon/ara/scenario/postman/service/PostmanScenarioIndexerService.java
> fix: ignore null and empty subfolders

- charts/candidate/Chart.yaml
- charts/candidate/values.yaml
- code/api/api/pom.xml
- code/api/database/pom.xml
- code/api/generated-cucumber-report/pom.xml
- code/api/jacoco-aggregation/pom.xml
- code/api/lib/pom.xml
- code/api/pom.xml
> chore: update versions

- charts/candidate/Chart.yaml
- charts/candidate/values.yaml
- code/api/api/pom.xml
- code/api/api/src/main/java/com/decathlon/ara/scenario/common/upload/ScenarioUploader.java
- code/api/database/pom.xml
- code/api/database/src/main/java/com/decathlon/ara/domain/Scenario.java
- code/api/generated-cucumber-report/pom.xml
- code/api/jacoco-aggregation/pom.xml
- code/api/lib/pom.xml
- code/api/pom.xml
When removing the scenario, remove functionality association to avoid association table foreign key problem.
https://thorben-janssen.com/hibernate-tips-the-best-way-to-remove-entities-from-a-many-to-many-association/
> fix: remove scenario in ScenarioUploader

- charts/stable/Chart.yaml
- charts/stable/values.yaml
Release 9.2.1
Copy candidate to stable Release 9.2.1
> chore: release 9.2.1

- code/core-api/pom.xml
- code/core-api/src/main/resources/application-db-h2.yaml
- code/core-api/src/main/resources/application-db-postgresql.yaml
- code/core-api/src/main/resources/application.yaml
- code/core-api/src/main/resources/config-database.yaml
- code/core-api/src/main/resources/db/changelog/db.changelog-master-h2.yaml
- code/core-api/src/main/resources/db/changelog/db.changelog-master-postgresql.yaml
Add db selection management
Add spring doc
Add liquibase
Add some spring boot yaml to have db selection management
Add spring doc
Add liquibase
> feat: add db management

- charts/candidate/Chart.yaml
- charts/candidate/values.yaml
- code/api/api/pom.xml
- code/api/api/src/main/resources/logback-spring.xml
- code/api/database/pom.xml
- code/api/generated-cucumber-report/pom.xml
- code/api/jacoco-aggregation/pom.xml
- code/api/lib/pom.xml
- code/api/pom.xml
- code/core-api/pom.xml
- code/core-api/src/main/resources/logback-spring.xml
- doc/tech/LOGGING.adoc
Add log management
confère doc/tech/LOGGING.adoc
> feat: add logging management

- charts/candidate/Chart.yaml
- charts/candidate/templates/_helpers.tpl
- charts/candidate/templates/config.yaml
- charts/candidate/templates/deploy-api.yaml
- charts/candidate/values.yaml
- code/api/api/pom.xml
- code/api/api/src/main/resources/application.yaml
- code/api/api/src/main/resources/logback-spring.xml
- code/api/database/pom.xml
- code/api/generated-cucumber-report/pom.xml
- code/api/jacoco-aggregation/pom.xml
- code/api/lib/pom.xml
- code/api/pom.xml
- code/core-api/pom.xml
- code/core-api/src/main/resources/application.yaml
- code/core-api/src/main/resources/logback-spring.xml
- doc/tech/LOGGING.adoc
Allow to change logging in the chart
Logging mode list in the chart
> fix: logging system

- charts/stable/Chart.yaml
- charts/stable/templates/_helpers.tpl
- charts/stable/templates/config.yaml
- charts/stable/templates/deploy-api.yaml
- charts/stable/values.yaml
> chore: release 9.3.1

- charts/candidate/Chart.yaml
- charts/candidate/values.yaml
- code/api/api/pom.xml
- code/api/api/src/main/java/com/decathlon/ara/scenario/common/upload/ScenarioUploader.java
- code/api/api/src/main/java/com/decathlon/ara/scenario/cucumber/resource/CucumberResource.java
- code/api/api/src/main/java/com/decathlon/ara/scenario/cucumber/upload/CucumberScenarioUploader.java
- code/api/api/src/main/java/com/decathlon/ara/scenario/postman/upload/PostmanScenarioUploader.java
- code/api/database/pom.xml
- code/api/database/src/main/java/com/decathlon/ara/domain/Error.java
- code/api/generated-cucumber-report/pom.xml
- code/api/jacoco-aggregation/pom.xml
- code/api/lib/pom.xml
- code/api/pom.xml
> fix: get rid of concurrency issue when purging executions

- charts/candidate/Chart.yaml
- charts/candidate/values.yaml
- code/api/api/pom.xml
- code/api/api/src/main/java/com/decathlon/ara/purge/service/PurgeService.java
- code/api/api/src/test/java/com/decathlon/ara/scheduler/purge/PurgeServiceTest.java
- code/api/database/pom.xml
- code/api/database/src/main/java/com/decathlon/ara/repository/ExecutionRepository.java
- code/api/generated-cucumber-report/pom.xml
- code/api/jacoco-aggregation/pom.xml
- code/api/lib/pom.xml
- code/api/pom.xml
Improve execution purge
Improve execution purge
> chore: improve execution purge

- README.adoc
- charts/candidate/Chart.yaml
- charts/candidate/values.yaml
- code/Makefile
- code/api/Makefile
- code/api/api/pom.xml
- code/api/api/src/main/java/com/decathlon/ara/web/rest/authentication/UserResource.java
- code/api/api/src/test/java/com/decathlon/ara/authentication/UserResourceTest.java
- code/api/database/pom.xml
- code/api/generated-cucumber-report/pom.xml
- code/api/jacoco-aggregation/pom.xml
- code/api/lib/pom.xml
- code/api/pom.xml
- code/docker-compose.dev.yaml
User OAuth2User if OIDCUser is not defined and a blank user if none.
Manage null pointer exception on OIDCUser.
> fix: oauth2-user

- code/api/migration-h2.yaml
- code/api/migration-mysql.yaml
- code/api/migration-postgresql.yaml
> fix: make liquibase diff

- charts/candidate/Chart.yaml
- code/web-ui/package-lock.json
- code/web-ui/package.json
- code/web-ui/src/service/rememberurl.service.js
ARA-205
Query parameters are lost after login. Ensure they are not.
Query parameters are lost after login. Ensure they are not.
> fix: remember url parameters

- code/api/api/src/main/java/com/decathlon/ara/purge/scheduler/PurgeTaskScheduler.java
- code/api/api/src/main/resources/application.yaml
- code/api/api/src/test/java/com/decathlon/ara/purge/scheduler/PurgeTaskSchedulerTest.java
> chore: purge executions using cron

- .github/workflows/build-api.yaml
- code/docker-compose.yaml
- code/tests/Makefile
- code/tests/README.md
- code/tests/data/clear-data.sql
- code/tests/data/tests-project.sql
- code/tests/docker-compose-tests.yaml
- code/tests/pom.xml
- code/tests/src/test/java/TestParallel.java
- code/tests/src/test/java/features/access-home-page.feature
- code/tests/src/test/java/features/run-the-purge.feature
- code/tests/src/test/java/templates/date.feature
Add integration tests
Add integration tests
> feat: add integration tests

- .husky/prepare-commit-msg
- README.adoc
- package-lock.json
- package.json
Add commit conventions and developer tool associate
Add angular commit convention and git hooks husky and commitizen to help developer to build conventional commit
> ci: add commit conventions

- code/api/api/src/main/java/com/decathlon/ara/purge/service/PurgeService.java
- code/api/api/src/main/java/com/decathlon/ara/service/util/DateService.java
- code/api/api/src/test/java/com/decathlon/ara/service/util/DateServiceTest.java
> chore: log execution purge total duration

- charts/candidate/Chart.yaml
- charts/candidate/values.yaml
- code/api/api/pom.xml
- code/api/database/pom.xml
- code/api/database/src/main/java/com/decathlon/ara/domain/Communication.java
- code/api/database/src/main/java/com/decathlon/ara/domain/Country.java
- code/api/database/src/main/java/com/decathlon/ara/domain/CycleDefinition.java
- code/api/database/src/main/java/com/decathlon/ara/domain/Project.java
- code/api/database/src/main/java/com/decathlon/ara/domain/RootCause.java
- code/api/database/src/main/java/com/decathlon/ara/domain/Setting.java
- code/api/database/src/main/java/com/decathlon/ara/domain/Severity.java
- code/api/database/src/main/java/com/decathlon/ara/domain/Source.java
- code/api/database/src/main/java/com/decathlon/ara/domain/Team.java
- code/api/database/src/main/java/com/decathlon/ara/domain/TechnologySetting.java
- code/api/database/src/main/java/com/decathlon/ara/domain/Type.java
- code/api/database/src/main/resources/db/changelog/changes/h2/20211125174155-not_null_constraints.yaml
- code/api/database/src/main/resources/db/changelog/changes/mysql/20211125171000-not_null_constraints.yaml
- code/api/database/src/main/resources/db/changelog/changes/postgresql/20211125164648-not_null_constraints.yaml
- code/api/database/src/main/resources/db/changelog/db.changelog-master-h2.yaml
- code/api/database/src/main/resources/db/changelog/db.changelog-master-mysql.yaml
- code/api/database/src/main/resources/db/changelog/db.changelog-master-postgresql.yaml
- code/api/generated-cucumber-report/pom.xml
- code/api/jacoco-aggregation/pom.xml
- code/api/lib/pom.xml
- code/api/pom.xml
- code/web-ui/package-lock.json
- code/web-ui/package.json
- code/web-ui/src/components/crud.vue
- code/web-ui/src/components/functionality-node.vue
- code/web-ui/src/views/management-types.vue
> fix: remove web-ui bugs

- .github/workflows/build-api.yaml
- .github/workflows/build-web-ui.yaml
- README.adoc
- code/api/.releaserc.json
- code/web-ui/.releaserc.json
Add semantic release in dry-run mode for api and web-ui
Add:
* Github action semantic release
* Add config for api
* Add config for web-ui
> ci(build): add semantic release mode for build-api and web-ui

- .github/cr-candidate-config.yaml
- .github/cr-stable-config.yaml
- .github/workflows/build-api.yaml
- .github/workflows/build-web-ui.yaml
- .github/workflows/charts-lint.yaml
- .github/workflows/charts-release.yaml
- README.adoc
- charts/candidate/.helmignore
- charts/candidate/.releaserc.json
- charts/candidate/templates/_helpers.tpl
- charts/candidate/templates/config.yaml
- charts/candidate/templates/deploy-api.yaml
- charts/candidate/templates/deploy-db.yaml
- charts/candidate/templates/deploy-ui.yaml
- charts/candidate/templates/ingress.yaml
- charts/candidate/templates/oauth2-mock.yaml
- code/Makefile
* Generate release note for charts by semantic release
* Auto upgrade chart by semantic release
* Use release note generate by semantic release in chart-releaser
* Use main github action for semantic release
* remove `-stable` suffix from main ara chart (the stable one)
* remove chart name from service name in the chart
* Impact charts
* Github actions
* Main ara workflow
> ci: update chart workflow

- .github/scripts/requirements.txt
- .github/scripts/upgrade-component.py
- .github/workflows/build-api.yaml
- .github/workflows/build-web-ui.yaml
Create a pr with next branch containing upgrade change
Add a step in workflow to upgrade candidate with new component version thanks to a python script
> chore(charts): auto update charts candidate

- .github/scripts/upgrade-component.py
- charts/candidate/values.yaml
- code/Makefile
* Update web-ui and api component version in candidate chart
* Fix upgrade-component script (replace tags by tag)
* add a make command to update manually component version
You now use the following command locally in `code` directory :
`make update-ui-component`
`make update-api-component`
> chore: next candidate version

- code/api/database/src/main/resources/db/changelog/changes/mysql/20211125171000-not_null_constraints.yaml
- code/api/database/src/main/resources/db/changelog/changes/postgresql/20211125164648-not_null_constraints.yaml
Fix apply not null contraint
move sql pre apply not BEFORE not null contraint
> fix(api): move not null contraint AFTER pre apply fullfill

- .github/workflows/build-core-api.yaml
- .github/workflows/build-oauth2-dev-server.yaml
- charts/candidate/templates/_helpers.tpl
- charts/candidate/templates/deploy-api.yaml
- charts/candidate/templates/oauth2-mock.yaml
- code/api/api/src/main/resources/application.yaml
- code/web-ui/src/components/top-menu.vue
* Use channel (candidate/stable) in version link
* add channel in actuator fill in by the chart
* use channel in new version link in front
> fix(application): use channel in version link

- .github/workflows/build.yaml
- code/api/Makefile
- code/api/api/pom.xml
- code/api/api/src/main/java/com/decathlon/ara/service/ErrorService.java
- code/api/api/src/main/java/com/decathlon/ara/service/ProblemService.java
- code/api/api/src/main/resources/application.yaml
- code/api/api/src/test/java/com/decathlon/ara/repository/ErrorRepositoryIT.java
- code/api/api/src/test/java/com/decathlon/ara/repository/custom/impl/QErrorTest.java
- code/api/database/pom.xml
- code/api/database/src/main/java/com/decathlon/ara/configuration/QueryDslConfiguration.java
- code/api/database/src/main/java/com/decathlon/ara/domain/QError.java
- code/api/database/src/main/java/com/decathlon/ara/domain/QProblem.java
- code/api/database/src/main/java/com/decathlon/ara/repository/custom/ErrorRepositoryCustom.java
- code/api/database/src/main/java/com/decathlon/ara/repository/custom/ProblemRepositoryCustom.java
- code/api/database/src/main/java/com/decathlon/ara/repository/custom/impl/ErrorRepositoryImpl.java
- code/api/database/src/main/java/com/decathlon/ara/repository/custom/impl/ProblemRepositoryImpl.java
- code/api/generated-cucumber-report/pom.xml
- code/api/lib/pom.xml
- code/core-api/pom.xml
- code/docker-compose.yaml
- code/oauth2-dev-server/pom.xml
- code/web-ui/package-lock.json
Upgrade to spring-boot 2.6.2
* Upgrade to spring-boot 2.6.2
* Upgrade related dep like query dsl
* Remove cyclic IoC
> chore(api): upgrade spring-boot to 2.6.2

- .github/workflows/build-core-api.yaml
- .github/workflows/build-oauth2-dev-server.yaml
- .github/workflows/build.yaml
- .github/workflows/charts-lint.yaml
- code/api/database/src/main/resources/db/changelog/changes/h2/20220125165550-change_data_type.yaml
- code/api/database/src/main/resources/db/changelog/changes/mysql/20220125173016-delete_cascade_on_problem_occurrences.yaml
- code/api/database/src/main/resources/db/changelog/changes/postgresql/20220125164557-remove-unexpected-index.yaml
- code/api/database/src/main/resources/db/changelog/db.changelog-master-h2.yaml
- code/api/database/src/main/resources/db/changelog/db.changelog-master-mysql.yaml
- code/api/database/src/main/resources/db/changelog/db.changelog-master-postgresql.yaml
Remove unexpected index in the liquibase
Run liquibase diff postgresql to make liquibase and hibernate data model iso
> fix(api): remove unexpected index

- .github/workflows/build.yaml
Fix path filter with master version
Fix path filter with master version
Use global path filter
> fix(ci): use global path filter

- charts/candidate/templates/ingress.yaml
update apiVersion from networking.k8s.io/v1beta1 to networking.k8s.io/v1
Update apiVersion of ingress
Change apiVersion from networking.k8s.io/v1beta1 to networking.k8s.io/v1 
> feat(charts): update apiVersion of ingress

- charts/candidate/templates/ingress.yaml
- charts/candidate/values.yaml
add spec.ingressClassName
Add ingress class value
Allow to specify ingress class in ara ingress
> feat(charts): add ingress class

- .github/pull_request_template.md
- .github/workflows/build-oauth2-dev-server.yaml
- .github/workflows/build.yaml
- .husky/prepare-commit-msg
- README.adoc
Fix a problem of libxml install in the ci
Fix a problem of libxml install in the ci
> fix(ci): use libxml2-utils

- code/api/api/pom.xml
- code/api/database/pom.xml
- code/api/generated-cucumber-report/pom.xml
- code/api/lib/pom.xml
- code/core-api/pom.xml
- code/oauth2-dev-server/pom.xml
> fix(spring): Spring Boot version update

- code/api/api/src/main/java/com/decathlon/ara/cartography/AraExporter.java
- code/api/api/src/main/java/com/decathlon/ara/defect/jira/adapter/JiraDefectAdapter.java
- code/api/api/src/main/java/com/decathlon/ara/defect/jira/api/JiraRestClient.java
- code/api/api/src/main/java/com/decathlon/ara/scenario/cucumber/indexer/CucumberScenariosIndexer.java
- code/api/api/src/main/java/com/decathlon/ara/scenario/postman/indexer/PostmanScenariosIndexer.java
- code/api/api/src/main/java/com/decathlon/ara/service/TechnologySettingService.java
- code/api/generated-cucumber-report/src/main/java/ara/demo/HooksGlue.java
> chore: reduce technical debt

- code/web-ui/src/components/functionality-node.vue
> fix: remove css property duplication

- code/api/api/src/main/java/com/decathlon/ara/loader/DemoSettingsLoader.java
- code/web-ui/src/components/functionality-node.vue
- code/web-ui/src/components/top-menu.vue
- code/web-ui/src/styles/common.css
- code/web-ui/src/views/functionality-cartography.vue
> fix: remove non regression bugs

- code/api/api/src/main/resources/application-oauth2-custom.yaml
The application behavior wont change
Add spi configuration in order to deploy in the testing teams serverless stack
> feat(functionality): add config to deploy in CEP monitoring stack

- code/api/api/src/main/java/com/decathlon/ara/Messages.java
- code/api/api/src/main/java/com/decathlon/ara/web/rest/ExecutionResource.java
> refactor: remove typo on variable

- .github/workflows/main.yml
> github action update

- .github/workflows/releaseCharts2.yml
> Update and rename main.yml to releaseCharts2.yml

- code/api/api/src/main/java/com/decathlon/ara/ci/service/ExecutionIndexerService.java
> fix: :ambulance: unsuported operation on list

- .github/workflows/build.yaml
- code/api/.releaserc.json
- code/web-ui/.releaserc.json
> Test update build
